# Generated by Django 6.0.2 on 2026-03-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Store', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
