# Generated by Django 6.0.2 on 2026-03-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliveryoption_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
